name: Deploy Automático KingHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Node.js e Gerar Build do Vite
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências visuais e compilar
        run: |
          npm install
          npm run build

      - name: Fazer Deploy via SSH na KingHost
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 191.6.223.44
          username: bs
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/mercadolandia_backend
            git pull
            php composer.phar install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan optimize:clear